version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    networks:
      - my_bridge_network
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  my_bridge_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
