spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example_db
    username: root
    password: example_root_password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: off
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 50
          fetch_size: 100
        order_inserts: true
        order_updates: true
        default_batch_fetch_size: 16
      javax:
        persistence:
          validation:
            mode: none

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
